### PR TITLE
Hello, I am creating documentation in english for BASM

### PR DESCRIPTION
**Pull request by 0ank**
It is not ready yet, but I want to open this pull request before You archive this repo.
I'm sorry that a lot of things are in one commit, but I was working on repo cloned from this and I did not have any permissions, so I create one commit in my fork.

I also have some questions:
- Does `arl` stands for "Array Remove eLements"?
- 'a' in ax stands for accumulator, 'b' in bx for base, 'c' in cx for counter and 'd' in dx for data. For what stand 'e' in ex, 'f' in fx, 'g' in gx, and 'h' in hx?

### CODE REVIEW

**Comment by piepert** [comment]
Wow, I would've never thought someone would show much interest in this project! If you need any more help, just tell me.

> Does `arl` stands for "Array Remove eLements"?

Yes, that's right.

> 'a' in ax stands for accumulator, 'b' in bx for base, 'c' in cx for counter and 'd' in dx for data. For what stand 'e' in ex, 'f' in fx, 'g' in gx, and 'h' in hx?

To speak truth, I didn't really plan BASM. I just have a weird sense for aesthetics. Assembly-like syntaxes just hit it. So I made BASM. At that time I didn't even know what 'ax', 'bx', ... stand for. So I just extended them, because... why wouldn't I :D? I just wanted to learn a bit about language design and extend my programming skills. So there is no big meaning behind the other register names.

One question to you: Did you read all the source to create this documentation? I have an old PDF file (I don't even know if I ever published it) where I documented all commands (unfortunately only in German). I could translate it into English if you need it. There is also a list of all abbreviations.

**Comment by 0ank** [comment]
Thank you for answering me.
> Did you read all the source to create this documentation?

Yes, I am reading all the source "just-in-time".
> I could translate it into English if you need it. There is also a list of all abbreviations.

It isn't neccessary, all of the abbreviations are in the source (excluding arl).

I have one more question: Why *Binary* Assembly?

And congratulations for creating a small compiler for such an elaborate language.

**Comment by piepert** [comment]
> I have one more question: Why Binary Assembly?

Intentionally I wanted to create a transpiler from BASM to one of my other projects. The name derived from this project. Then, as I started writing the code, I changed the plan and started just creating something different, with an assembly-like syntax. So there is no big background behind the name any more. As I said, I didn't plan very much and just kept going on and on.

**Comment by 0ank** [comment]
I added checking in div.hpp whether register is 0 in or not to help programmers finding error, because C++ source error can be at another line. Can you tell me how to check variable's value? I didn't find any getValue() or something like this for variables.

But if you don't want me to change your code, I will undo those changes.

**Comment by 0ank** [comment]
I closed this pull request because I see that this project is no longer maintained and it makes no sense to contribute to it.

**Pull request closed without merging**
